CREATE TABLE authors
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255),
    version INTEGER,
    CONSTRAINT pk_authors PRIMARY KEY (id)
);

insert into authors (name, version) values ('J.K. Rowling',1);
insert into authors (name, version) values ('George R.R. Martin',1);
insert into authors (name, version) values ('J.R.R. Tolkien',1);
insert into authors (name, version) values ('Gabriel García Márquez',1);
insert into authors (name, version) values ('Stephen King',1);
insert into authors (name, version) values ('Isaac Asimov',1);