apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-customers
  namespace: calechon-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-customers
  template:
    metadata:
      labels:
        app: app-customers
    spec:
      containers:
        - name: app-customers
          image: xd456/app-customers:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: books-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: books-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: books-secret
                  key: SPRING_DATASOURCE_PASSWORD
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: books-config
                  key: SERVER_PORT
            - name: SPRING_CLOUD_CONSUL_HOST
              valueFrom:
                configMapKeyRef:
                  name: books-config
                  key: CONSUL_HOST
            - name: SPRING_CLOUD_CONSUL_PORT
              valueFrom:
                configMapKeyRef:
                  name: books-config
                  key: CONSUL_PORT
            - name: MANAGEMENT_OTLP_TRACING_ENDPOINT
              value: "http://jaeger:4318/v1/traces"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: app-customers
  namespace: calechon-dev
spec:
  type: ClusterIP
  selector:
    app: app-customers
  ports:
    - port: 8080
      targetPort: 8080
      