apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-books
  namespace: books-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-books
  template:
    metadata:
      labels:
        app: app-books
    spec:
      containers:
        - name: app-books
          image: xd456/app-books:latest # Asegurate de cambiar 'xd456' por tu usuario de Docker Hub si subes la imagen
          ports:
            - containerPort: 8080
          env:
            - name: QUARKUS_DATASOURCE_JDBC_URL
              valueFrom:
                configMapKeyRef:
                  name: books-config
                  key: QUARKUS_DATASOURCE_JDBC_URL
            - name: QUARKUS_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: books-secret
                  key: QUARKUS_DATASOURCE_USERNAME
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: books-secret
                  key: QUARKUS_DATASOURCE_PASSWORD
            - name: QUARKUS_HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: books-config
                  key: QUARKUS_HTTP_PORT
            - name: CONSUL_HOST
              valueFrom:
                configMapKeyRef:
                  name: books-config
                  key: CONSUL_HOST
            - name: CONSUL_PORT
              valueFrom:
                configMapKeyRef:
                  name: books-config
                  key: CONSUL_PORT
            - name: QUARKUS_FLYWAY_MIGRATE_AT_START
              valueFrom:
                configMapKeyRef:
                  name: books-config
                  key: QUARKUS_FLYWAY_MIGRATE_AT_START
          
          # Readiness y Liveness Probes exigidos en la rubrica
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10

          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: app-books
  namespace: books-app
spec:
  type: ClusterIP
  selector:
    app: app-books
  ports:
    - port: 8080
      targetPort: 8080
