apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-books
  #namespace: books-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-books
  template:
    metadata:
      labels:
        app: app-books
    spec:
      containers:
        - name: app-books
          image: xd456/app-books:latest
          ports:
            - containerPort: 8080
          env:
            - name: QUARKUS_DATASOURCE_JDBC_URL
              valueFrom:
                configMapKeyRef:
                  name: books-config
                  key: QUARKUS_DATASOURCE_JDBC_URL
            - name: QUARKUS_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: books-secret
                  key: QUARKUS_DATASOURCE_USERNAME
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: books-secret
                  key: QUARKUS_DATASOURCE_PASSWORD
            - name: QUARKUS_HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: books-config
                  key: QUARKUS_HTTP_PORT
            - name: CONSUL_HOST
              valueFrom:
                configMapKeyRef:
                  name: books-config
                  key: CONSUL_HOST
            - name: CONSUL_PORT
              valueFrom:
                configMapKeyRef:
                  name: books-config
                  key: CONSUL_PORT
            - name: OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: books-config
                  key: OTLP_ENDPOINT
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: app-books
  #namespace: books-app
spec:
  type: ClusterIP
  selector:
    app: app-books
  ports:
    - port: 8080
      targetPort: 8080


      