apiVersion: v1
kind: Secret
metadata:
  name: books-secret
  namespace: books-app
type: Opaque
stringData:
  QUARKUS_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_USERNAME: "postgres"
  QUARKUS_DATASOURCE_PASSWORD: "postgres"
  SPRING_DATASOURCE_PASSWORD: "postgres"
