CREATE TABLE IF NOT EXISTS customers
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    email      VARCHAR(255) NOT NULL,
    phone      VARCHAR(50),
    address    VARCHAR(255),
    created_at TIMESTAMP,
    CONSTRAINT pk_customers PRIMARY KEY (id),
    CONSTRAINT uk_customers_email UNIQUE (email)
);
