# -- Crear la imagen
# docker build -f src/main/docker/Dockerfile.jvm -t xd456/app-customers .
# docker login
# docker push xd456/app-customers
# docker logout
#

FROM docker.io/eclipse-temurin:25.0.3_9-jre-alpine

ENV LANGUAGE='en_US:en'

RUN mkdir /app
WORKDIR /app

COPY build/quarkus-app/lib ./lib
COPY build/quarkus-app/quarkus ./quarkus
COPY build/quarkus-app/app ./app
COPY build/quarkus-app/quarkus-run.jar app.jar

CMD ["java", "-jar", "app.jar"]