quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/books
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres

#ports
quarkus.http.port=8080
quarkus.http.host=0.0.0.0

# Configurar el cliente REST para que use Stork con el nombre "authors-api"
quarkus.rest-client.authors-api.url=stork://authors-api

# Configurar Stork para que busque "authors-api" usando Consul
quarkus.stork.authors-api.service-discovery.type=consul
quarkus.stork.authors-api.service-discovery.consul-host=${consul.host}
quarkus.stork.authors-api.service-discovery.consul-port=${consul.port}
quarkus.stork.authors-api.service-discovery.application=app-authors
quarkus.stork.authors-api.service-discovery.refresh-period=5s

# CORS
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=/.*/
quarkus.http.cors.methods=GET, POST, PUT, DELETE, OPTIONS, HEAD

# Jaeger
quarkus.application.name=${app.name}
quarkus.otel.traces.sampler=always_on
quarkus.otel.exporter.otlp.traces.endpoint=http://localhost:4317